#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""verify_reference.py

Regenerates dev/reference/known_points.json (or verifies it) using pyproj
with the exact EPSG PROJ.4 strings for EPSG:3375 and EPSG:3376, then checks
the committed fixtures are still in agreement (matching the Suunto reference
project's methodology).

This is a DEV-ONLY tool (pyproj is not a watch dependency).

Usage:
    python test/verify_reference.py          # verify committed fixtures
    python test/verify_reference.py --write  # regenerate the fixtures
"""
import json
import os
import sys

from pyproj import Transformer

# PROJ.4 strings verbatim from epsg.io (EPSG registry), verified 2026-08-08.
P3375 = (
    "+proj=omerc +no_uoff +lat_0=4 +lonc=102.25 "
    "+alpha=323.025796466667 +gamma=323.130102361111 +k=0.99984 "
    "+x_0=804671 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
)
P3376 = (
    "+proj=omerc +no_uoff +lat_0=4 +lonc=115 "
    "+alpha=53.31580995 +gamma=53.1301023611111 +k=0.99984 "
    "+x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
)

# (lon, lat) sample points covering both areas of use.
SAMPLES_3375 = [
    (101.686855, 3.139003),   # Kuala Lumpur
    (101.686, 3.138),         # PRD TC-02 point
    (100.317367, 5.414895),   # Penang
    (103.831435, 1.352083),   # Johor Bahru
    (103.144278, 3.052345),   # Pahang interior
    (102.25, 4.0),            # projection origin
    (99.733333, 6.133333),    # Langkawi / far west
    (104.0, 1.0),             # south-east tip
]
SAMPLES_3376 = [
    (110.33, 1.55),           # Kuching, Sarawak
    (113.98, 4.39),           # Miri, Sarawak
    (116.0, 5.97),            # Kota Kinabalu, Sabah
    (118.06, 5.35),           # Sandakan
    (115.0, 4.0),             # projection origin
]


def compute():
    out = {
        "description": (
            "Authoritative reference outputs for GDM2000 RSO (EPSG:3375/3376). "
            "Generated by pyproj with epsg.io parameters. Used to validate "
            "the Monkey C math to <=1 m."
        ),
        "crs": [],
    }
    for epsg, proj4, samples in (
        ("EPSG:3375", P3375, SAMPLES_3375),
        ("EPSG:3376", P3376, SAMPLES_3376),
    ):
        t = Transformer.from_crs("EPSG:4326", proj4, always_xy=True)
        points = []
        for lon, lat in samples:
            e, n = t.transform(lon, lat)
            points.append({
                "lon": lon,
                "lat": lat,
                "easting": round(e, 4),
                "northing": round(n, 4),
            })
        out["crs"].append({
            "epsg": epsg,
            "proj4": proj4,
            "ellipsoid": "GRS80 (a=6378137, 1/f=298.257222101)",
            "generator": "pyproj %s" % (__import__("pyproj").__version__),
            "points": points,
        })
    return out


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "..", "dev", "reference", "known_points.json")
    fresh = compute()

    if "--write" in sys.argv:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(fresh, f, indent=2)
            f.write("\n")
        print("Wrote %s" % os.path.normpath(path))
        return 0

    with open(path, "r", encoding="utf-8") as f:
        committed = json.load(f)

    worst = 0.0
    ok = True
    for cnew in fresh["crs"]:
        for pnew in cnew["points"]:
            pold = next(
                p for p in next(
                    c for c in committed["crs"] if c["epsg"] == cnew["epsg"]
                )["points"]
                if abs(p["lon"] - pnew["lon"]) < 1e-9 and abs(p["lat"] - pnew["lat"]) < 1e-9
            )
            d = max(abs(pnew["easting"] - pold["easting"]),
                    abs(pnew["northing"] - pold["northing"]))
            worst = max(worst, d)
            if d > 0.001:
                ok = False
                print("MISMATCH %s (%s, %s): committed=(%.4f, %.4f) fresh=(%.4f, %.4f)"
                      % (cnew["epsg"], pnew["lon"], pnew["lat"],
                         pold["easting"], pold["northing"],
                         pnew["easting"], pnew["northing"]))
    print("Worst fixture drift vs pyproj: %.6f m" % worst)
    print("RESULT: %s" % ("OK" if ok else "FAIL"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
